
# Some setups before using find_package is needed
# Extend CMAKE_MODULE_PATH and CMAKE_PREFIX_PATH so that CMake can find the
# configuration files generated by conan in the build directory
set(CMAKE_MODULE_PATH "${CMAKE_BINARY_DIR}" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "${CMAKE_BINARY_DIR}" ${CMAKE_PREFIX_PATH})

find_package(ZeroMQ REQUIRED)
find_package(cppzmq REQUIRED)
find_package(spdlog REQUIRED)